# Generated by Django 3.2.4 on 2021-06-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ztp5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishmodel',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dishmodel',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='IngredientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(blank=True, max_length=30, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ztp5.dishmodel')),
            ],
        ),
    ]
