# Generated by Django 3.2.4 on 2021-06-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztp5', '0002_auto_20210619_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientmodel',
            old_name='ingredient',
            new_name='name',
        ),
    ]
