# Generated by Django 3.2.4 on 2021-06-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztp5', '0003_rename_ingredient_ingredientmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientmodel',
            old_name='name',
            new_name='ingredient',
        ),
    ]
