# Generated by Django 3.2.4 on 2021-06-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztp5', '0004_rename_name_ingredientmodel_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishmodel',
            name='ingredients',
        ),
    ]
