# Generated by Django 3.2.4 on 2021-06-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztp5', '0009_alter_dishmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
